name: notepadng
adopt-info: notepadng

grade: devel
confinement: strict
icon: dist/icons/hicolor/scalable/apps/org.notepadng.Notepadng.svg
base: core24

apps:
  notepadng:
    common-id: org.notepadng.Notepadng
    command: usr/bin/notepadng
    desktop: usr/share/applications/org.notepadng.Notepadng.desktop
    extensions:
      - kde-neon-6
    plugs:
      - home

parts:
  qscintilla:
    plugin: nil
    stage-packages:
      - libqscintilla2-qt6-15
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libqscintilla2_qt6.so.*
      - usr/share/qt6/translations/qscintilla_*.qm

  uchardet:
    after:
      - qscintilla
    plugin: nil
    stage-packages:
      - libuchardet0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libuchardet.so.*

  notepadng:
    after:
      - uchardet
    parse-info:
      - dist/org.notepadng.Notepadng.appdata.xml
    build-packages:
      - pkgconf
      - libqscintilla2-qt6-dev
      - libuchardet-dev
    source: .
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_VARIANT="Snap"
    cmake-generator: Ninja
    prime:
      - usr/bin/notepadng
      - usr/share/applications/org.notepadng.Notepadng.desktop
      - usr/share/icons/hicolor/*/apps/org.notepadng.Notepadng.png
      - usr/share/icons/hicolor/scalable/apps/org.notepadng.Notepadng.svg
      - usr/share/metainfo/org.notepadng.Notepadng.appdata.xml
      - usr/share/notepadng
